version: '3'
services:
  app1:
    build: ./app
    container_name: app1
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "8081:80"

  app2:
    build: ./app
    container_name: app2
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "8082:80"

  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - "8080:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - app1
      - app2
